### ISSUE TITLE
[US] Edit Profile Page

### ISSUE THREAD

**Issue by Genna-C** [uofa-cmput404/404f23project-web-weavers#43]
## User Story
As an author, I want to be able to use my web-browser to manage my profile

## Subtasks

- [ ]  frontend: Build Profile editing 
- [ ]  middle: Integrate POST request API 
- [ ]  backend: POST Author Detail Request
